# Generated by Django 5.0.7 on 2024-07-11 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_state_city_userprofiletable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=40)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='UserProfileTable',
            new_name='UserProfile',
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('Description', models.TextField()),
                ('Stock', models.BigIntegerField()),
                ('Image', models.ImageField(upload_to='equipmentphotos')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sportcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Productcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Order_id', models.IntegerField()),
                ('Order_status', models.CharField(max_length=30)),
                ('Plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.equipment')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
