# Generated by Django 5.0.7 on 2024-07-11 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sportcategory_rename_userprofiletable_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(choices=[('delivery issues', 'Delivery issues'), ('payment issues', 'Payment issues'), ('other', 'Other')], max_length=30)),
                ('Complaint_date', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='productcart',
            old_name='Plant',
            new_name='Equipment',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='Order_id',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='Order_status',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.FloatField()),
                ('Comment', models.CharField(max_length=50)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Total_price', models.BigIntegerField()),
                ('Order_date', models.DateField()),
                ('Delivery_date', models.DateField()),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Pending', max_length=30)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productcart')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.BigIntegerField()),
                ('Payment_mode', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('other', 'Other')], max_length=30)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
