# Generated by Django 5.0.7 on 2024-07-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_sportcategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='Description',
        ),
    ]
