# Generated by Django 5.0.7 on 2024-07-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_equipment_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='Stock',
            new_name='Quantity',
        ),
    ]
