# Generated by Django 5.0.7 on 2024-07-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_stock_equipment_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
