# Generated by Django 5.0.4 on 2024-07-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_equipment_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='State',
        ),
        migrations.DeleteModel(
            name='Complain',
        ),
        migrations.RemoveField(
            model_name='state',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='User',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='Equipment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='User',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Equipment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='User',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='User',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='User',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='User',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='SportCategory',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Productcart',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
